const fs = require('fs');
const path = require('path');

// Configuration
const dataFile = path.join(__dirname, 'tools-data.json');
const toolsDir = path.join(__dirname, 'tools');

// Ensure the tools directory exists
if (!fs.existsSync(toolsDir)) {
    fs.mkdirSync(toolsDir, { recursive: true });
}

// Read Data
let toolsObj = [];
try {
    const rawData = fs.readFileSync(dataFile, 'utf8');
    toolsObj = JSON.parse(rawData);
} catch (e) {
    console.error("Failed to read tools-data.json. Did you create it?", e);
    process.exit(1);
}

// HTML Generator Template
const generateHtml = (tool) => {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Free online ${tool.name} tool. ${tool.desc} Secure, fast, and easy to use. No installation required.">
    <title>${tool.name} - Free Online Tool | ToolHub</title>
    
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="../css/styles.css">
</head>
<body class="light-mode">

    <!-- Sticky Header -->
    <header class="header">
        <div class="container header-content">
            <a href="../index.html" class="logo">
                <i class="fas fa-layer-group"></i> ToolHub
            </a>
            <div class="header-actions">
                <button id="theme-toggle" class="icon-btn" aria-label="Toggle Dark Mode">
                    <i class="fas fa-moon"></i>
                </button>
            </div>
        </div>
    </header>

    <!-- AdSense Header Slot -->
    <div class="ad-container ad-header">
        <div class="ad-placeholder">AdSense Header (728x90)</div>
    </div>

    <!-- Main Content -->
    <main class="main-content container">
        
        <!-- Breadcrumbs -->
        <nav aria-label="breadcrumb" style="margin: 1rem 0; color: var(--text-muted); font-size: 0.9rem;">
            <a href="../index.html" style="color: var(--primary);">Home</a> &gt; 
            <span>${tool.category}</span> &gt; 
            <strong>${tool.name}</strong>
        </nav>

        <section class="tool-header">
            <h1><i class="${tool.icon}"></i> ${tool.name}</h1>
            <p style="color: var(--text-muted); font-size: 1.1rem;">${tool.desc}</p>
        </section>

        <!-- Tool Workspace (This is where the JS magic will happen) -->
        <section class="tool-workspace" id="workspace">
            <h2>Start using ${tool.name}</h2>
            <div style="text-align: center; margin-top: 2rem;">
                <p>🔧 <strong>Tool under construction or fully loaded via JS below.</strong></p>
                <div id="tool-ui-container">
                    <!-- Specific Tool UI generated by script or embedded here -->
                </div>
            </div>
        </section>

        <!-- AdSense In-Content Slot -->
        <div class="ad-container" style="margin: 3rem auto;">
            <div class="ad-placeholder" style="width: 100%; height: 250px;">AdSense In-Article (Responsive)</div>
        </div>

        <!-- SEO Content -->
        <section class="tool-seo-content">
            <h2>What is ${tool.name}?</h2>
            <p>The <strong>${tool.name}</strong> is a free online utility that allows you to quickly and easily perform tasks related to ${tool.desc.toLowerCase()} 
            Built with modern web standards, this tool processes everything securely in your browser so your data never leaves your device.</p>
            
            <h3>Why use our ${tool.name}?</h3>
            <p>Unlike other platforms, ToolHub provides completely unrestricted access. Our solution is fast, mobile-friendly, and highly optimized for performance. 
            Whether you are on a smartphone, tablet, or desktop computer, you can rely on this tool to work perfectly.</p>

            <h3>How it works</h3>
            <p>Our tool runs complex algorithms entirely in-browser using modern APIs like Canvas, FileReader, or WebCrypto. 
            This means 100% privacy for your files and immediate results without waiting for server uploads or downloads.</p>

            <h2 style="margin-top: 3rem; border-bottom: 2px solid var(--border); padding-bottom: 1rem;">Frequently Asked Questions (FAQ)</h2>
            
            <div class="faq-item">
                <h3>Is ${tool.name} free to use?</h3>
                <p>Yes, all 100 tools on ToolHub are completely free to use with no hidden fees or subscriptions.</p>
            </div>
            
            <div class="faq-item">
                <h3>Is my data secure?</h3>
                <p>Absolutely. We use edge-computing and browser-level processing. Your files never touch our servers, guaranteeing complete privacy and security.</p>
            </div>
            
            <div class="faq-item">
                <h3>Does it work on mobile?</h3>
                <p>Yes, ToolHub is designed with a mobile-first approach. You can use this tool on Android, iOS, or any modern web browser perfectly.</p>
            </div>
        </section>

    </main>

    <!-- Footer -->
    <footer class="footer">
        <div class="container footer-content">
            <div class="footer-brand">
                <h3><i class="fas fa-layer-group"></i> ToolHub</h3>
                <p>100% Free online tools running directly in your browser. No server uploads required.</p>
            </div>
            <div class="footer-links">
                <h4>Legal</h4>
                <ul>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-bottom">
            <p>&copy; 2026 ToolHub. All rights reserved.</p>
        </div>
    </footer>

    <!-- Toast Container -->
    <div id="toast-container" class="toast-container"></div>

    <!-- Scripts -->
    <script src="../js/script.js"></script>
    <script>
        // Placeholder or simple scripts for the tool can go here
        // If it's a primary tool, we will overwrite the tool-workspace entirely
    </script>
</body>
</html>`;
};

// Generate Loop
let successCount = 0;
toolsObj.forEach(tool => {
    const filename = \`\${tool.id}.html\`;
    const filepath = path.join(toolsDir, filename);

    // Write file
    fs.writeFileSync(filepath, generateHtml(tool), 'utf8');
    successCount++;
});

console.log(\`✅ Successfully generated \${successCount} tool pages in /tools/\`);
